# Generated by Django 4.2.4 on 2023-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_createjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
