# Generated by Django 4.2.4 on 2023-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_createjob_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='description',
            field=models.TextField(),
        ),
    ]
