# Generated by Django 4.2.4 on 2023-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_createjob_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createjob',
            name='timestampmodel_ptr',
        ),
        migrations.AddField(
            model_name='createjob',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeStampModel',
        ),
    ]
