# Generated by Django 4.2.4 on 2023-08-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_createjob_timestampmodel_ptr_createjob_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='id',
        ),
        migrations.AddField(
            model_name='createjob',
            name='timestampmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.timestampmodel'),
            preserve_default=False,
        ),
    ]
