# Generated by Django 4.2.4 on 2023-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_createjob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='job_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
